# Tarea 05 — Pandas

En esta tarea trabajaremos con pequeños conjuntos de datos para practicar diferentes operaciones de **Pandas**.

El objetivo no es solamente obtener el resultado, sino investigar y comprender qué herramientas de Pandas permiten resolver cada problema.

# 1. Eliminar registros duplicados

Una empresa registra las compras realizadas por sus clientes. Por un problema en el sistema, algunos clientes aparecen más de una vez.

El `customer_id` identifica de manera única a cada cliente.

### Actividades

1. Identifica cuáles son los clientes que aparecen más de una vez.
2. Elimina los registros duplicados manteniendo **la primera aparición** de cada cliente.
3. Repite la operación manteniendo **la última aparición** y compara ambos resultados.

**Investiga:** `drop_duplicates()` y el parámetro que permite decidir qué aparición conservar.

In [7]:
# Creamos el DataFrame con algunos registros duplicados.

customers = pd.DataFrame({
    "customer_id": [101, 102, 103, 102, 104, 103, 105],
    "name": ["Ana", "Carlos", "Maria", "Carlos", "Pedro", "Maria", "Laura"],
    "city": ["Lima", "Arequipa", "Cusco", "Lima", "Tacna", "Arequipa", "Lima"],
    "purchase": [120, 250, 180, 300, 90, 220, 150]
})

customers

   customer_id    name      city  purchase
0          101     Ana      Lima       120
1          102  Carlos  Arequipa       250
2          103   Maria     Cusco       180
3          102  Carlos      Lima       300
4          104   Pedro     Tacna        90
5          103   Maria  Arequipa       220
6          105   Laura      Lima       150

In [8]:
# 1. Identificamos los registros que tienen un customer_id duplicado.

duplicated_customers = customers[customers["customer_id"].duplicated(keep=False)]

duplicated_customers

   customer_id    name      city  purchase
1          102  Carlos  Arequipa       250
2          103   Maria     Cusco       180
3          102  Carlos      Lima       300
5          103   Maria  Arequipa       220

In [9]:
# 2. Eliminamos duplicados conservando la primera aparición.

customers_first = customers.drop_duplicates(
    subset="customer_id",
    keep="first"
)

customers_first

   customer_id    name      city  purchase
0          101     Ana      Lima       120
1          102  Carlos  Arequipa       250
2          103   Maria     Cusco       180
4          104   Pedro     Tacna        90
6          105   Laura      Lima       150

In [10]:
# 3. Eliminamos duplicados conservando la última aparición.

customers_last = customers.drop_duplicates(
    subset="customer_id",
    keep="last"
)

customers_last

   customer_id    name      city  purchase
0          101     Ana      Lima       120
3          102  Carlos      Lima       300
4          104   Pedro     Tacna        90
5          103   Maria  Arequipa       220
6          105   Laura      Lima       150

### Explicación

- `duplicated(keep=False)` permite identificar todas las filas cuyo `customer_id` aparece más de una vez.
- `drop_duplicates()` elimina registros repetidos.
- `keep="first"` conserva la primera aparición.
- `keep="last"` conserva la última aparición.

Observa que para los clientes `102` y `103` cambia la información conservada dependiendo de la opción utilizada.

# 2. Agrupar, transformar el índice y ordenar resultados

Una empresa tiene información sobre las ventas realizadas por diferentes tiendas.

### Actividades

1. Calcula las **ventas totales por tienda**.
2. Convierte el resultado en un DataFrame convencional.
3. Ordena las tiendas desde la que obtuvo mayores ventas hasta la que obtuvo menores ventas e identifica la tienda con mayor facturación.

**Investiga:** `groupby()`, `reset_index()` y `sort_values()`.

In [11]:
# Creamos el DataFrame de ventas.

sales = pd.DataFrame({
    "store": ["A", "B", "A", "C", "B", "C", "A", "B"],
    "product": ["Laptop", "Laptop", "Phone", "Phone",
                "Phone", "Laptop", "Tablet", "Tablet"],
    "sales": [1200, 1500, 800, 950, 1100, 1700, 600, 900]
})

sales

  store product  sales
0     A  Laptop   1200
1     B  Laptop   1500
2     A   Phone    800
3     C   Phone    950
4     B   Phone   1100
5     C  Laptop   1700
6     A  Tablet    600
7     B  Tablet    900

In [12]:
# 1. Calculamos las ventas totales por tienda.

sales_by_store = sales.groupby("store")["sales"].sum()

sales_by_store

store
A    2600
B    3500
C    2650
Name: sales, dtype: int64

In [13]:
# 2. Convertimos el resultado en un DataFrame convencional.

sales_by_store = sales_by_store.reset_index()

sales_by_store

  store  sales
0     A   2600
1     B   3500
2     C   2650

In [14]:
# 3. Ordenamos las tiendas desde la mayor hasta la menor facturación.

sales_by_store = sales_by_store.sort_values(
    by="sales",
    ascending=False
)

sales_by_store

  store  sales
1     B   3500
2     C   2650
0     A   2600

### Resultado

La tienda que obtuvo la mayor facturación es la **tienda B**, con **3500** unidades monetarias.

La combinación de `groupby()`, `reset_index()` y `sort_values()` permite pasar de los datos originales a un resumen ordenado y fácil de analizar.

# 3. Construir una tabla resumen con `pivot_table()`

Un restaurante registra la cantidad de pedidos recibidos durante el almuerzo y la cena.

### Actividades

1. Construye una tabla donde las **filas sean los días**, las **columnas sean los tipos de comida (`meal`)** y los valores sean el **total de pedidos**.
2. Determina qué día tuvo más pedidos durante la cena y qué días tuvieron el mayor total de pedidos considerando almuerzo y cena.

**Investiga:** `pivot_table()`.

In [15]:
# Creamos el DataFrame de pedidos.

orders = pd.DataFrame({
    "day": ["Monday", "Monday", "Tuesday", "Tuesday",
            "Wednesday", "Wednesday", "Thursday", "Thursday"],
    "meal": ["Lunch", "Dinner", "Lunch", "Dinner",
             "Lunch", "Dinner", "Lunch", "Dinner"],
    "orders": [35, 50, 40, 65, 30, 70, 45, 60]
})

orders

         day    meal  orders
0     Monday   Lunch      35
1     Monday  Dinner      50
2    Tuesday   Lunch      40
3    Tuesday  Dinner      65
4  Wednesday   Lunch      30
5  Wednesday  Dinner      70
6   Thursday   Lunch      45
7   Thursday  Dinner      60

In [16]:
# 1. Construimos la tabla resumen utilizando pivot_table().

orders_pivot = orders.pivot_table(
    index="day",
    columns="meal",
    values="orders",
    aggfunc="sum"
)

orders_pivot

meal       Dinner  Lunch
day
Monday         50     35
Thursday       60     45
Tuesday        65     40
Wednesday      70     30

In [17]:
# 2. Calculamos el total de pedidos por día.

orders_pivot["Total"] = orders_pivot.sum(axis=1)

orders_pivot.sort_values(by="Total", ascending=False)

meal       Dinner  Lunch  Total
day
Thursday       60     45    105
Tuesday        65     40    105
Wednesday      70     30    100
Monday         50     35     85

### Resultado

- El mayor número de pedidos durante la **cena** corresponde a **Wednesday**, con 70 pedidos.
- Los días con mayor cantidad total de pedidos son **Tuesday** y **Thursday**, con 105 pedidos cada uno.

`pivot_table()` permite reorganizar los datos para analizar fácilmente dos dimensiones categóricas.

# 4. Trabajar con fechas y horas

Una empresa de logística registra la fecha y hora de entrega de sus paquetes. Sin embargo, la columna `delivery_time` está almacenada como texto.

### Actividades

1. Convierte `delivery_time` en una columna de tipo **datetime**.
2. Extrae de esa columna el **día de la semana** y la **hora** de cada entrega.
3. Crea una nueva columna llamada `delivery_period` clasificando las entregas como:
   - `Morning`: antes de las 12:00.
   - `Afternoon`: desde las 12:00 hasta antes de las 18:00.
   - `Evening`: desde las 18:00.
4. Cuenta cuántos paquetes fueron entregados en cada período.

**Investiga:** `pd.to_datetime()` y las propiedades `.dt` de Pandas.

In [18]:
# Creamos el DataFrame.
# Observa que delivery_time está almacenado inicialmente como texto.

deliveries = pd.DataFrame({
    "package_id": [1001, 1002, 1003, 1004, 1005],
    "customer": ["Ana", "Carlos", "Maria", "Pedro", "Laura"],
    "delivery_time": [
        "2026-08-20 08:35:00",
        "2026-08-20 14:20:00",
        "2026-08-21 09:15:00",
        "2026-08-21 18:45:00",
        "2026-08-22 11:30:00"
    ]
})

deliveries

   package_id customer        delivery_time
0        1001      Ana  2026-08-20 08:35:00
1        1002   Carlos  2026-08-20 14:20:00
2        1003    Maria  2026-08-21 09:15:00
3        1004    Pedro  2026-08-21 18:45:00
4        1005    Laura  2026-08-22 11:30:00

In [19]:
# 1. Convertimos delivery_time a un tipo datetime.

deliveries["delivery_time"] = pd.to_datetime(
    deliveries["delivery_time"]
)

deliveries.dtypes

package_id                int64
customer                 object
delivery_time    datetime64[ns]
dtype: object

In [20]:
# 2. Extraemos el día de la semana y la hora.

deliveries["day_of_week"] = deliveries["delivery_time"].dt.day_name()
deliveries["hour"] = deliveries["delivery_time"].dt.hour

deliveries

   package_id customer       delivery_time day_of_week  hour
0        1001      Ana 2026-08-20 08:35:00    Thursday     8
1        1002   Carlos 2026-08-20 14:20:00    Thursday    14
2        1003    Maria 2026-08-21 09:15:00      Friday     9
3        1004    Pedro 2026-08-21 18:45:00      Friday    18
4        1005    Laura 2026-08-22 11:30:00    Saturday    11

In [21]:
# 3. Clasificamos cada entrega según la hora del día.

def classify_period(hour):
    if hour < 12:
        return "Morning"
    elif hour < 18:
        return "Afternoon"
    else:
        return "Evening"

deliveries["delivery_period"] = deliveries["hour"].apply(classify_period)

deliveries

   package_id customer       delivery_time day_of_week  hour delivery_period
0        1001      Ana 2026-08-20 08:35:00    Thursday     8         Morning
1        1002   Carlos 2026-08-20 14:20:00    Thursday    14       Afternoon
2        1003    Maria 2026-08-21 09:15:00      Friday     9         Morning
3        1004    Pedro 2026-08-21 18:45:00      Friday    18         Evening
4        1005    Laura 2026-08-22 11:30:00    Saturday    11         Morning

### Resultado

La información final permite analizar la fecha y hora de cada entrega y agruparlas por período:

- **Morning:** 3 paquetes
- **Afternoon:** 1 paquete
- **Evening:** 1 paquete

La propiedad `.dt` permite acceder a diferentes componentes de una columna datetime, como el día, mes, año, hora o día de la semana.