# Laboratorio 8: Introducción a NumPy y Pandas

Bienvenido al Laboratorio 8. En esta sesión daremos nuestros primeros pasos en las herramientas fundamentales para el análisis de datos. Aprenderemos a utilizar **NumPy**, el motor numérico de Python, y **Pandas**, la librería líder para la manipulación de datos estructurados.

## 📋 Tabla de Contenidos

1. [INTRODUCCIÓN A NUMPY](#-numpy)
2. [PANDAS: CARGA Y MANIPULACIÓN](#-pandas)
3. [MANEJO DE SERIES](#-series)
4. [DATAFRAMES: CREACIÓN Y OPERACIONES](#-dataframes)
5. [MÁSCARAS Y FILTROS](#-filtros)
6. [ORDENAMIENTO](#-sort)

---

<a id='-numpy'></a>
## 🔹 1: INTRODUCCIÓN A NUMPY

**NumPy** es una librería diseñada para realizar cálculos numéricos de alta eficiencia. Su estructura base es el `ndarray` (arreglo multidimensional o matriz).

Es fundamental entender que **Pandas se basa internamente en NumPy** para gestionar sus datos, lo que garantiza velocidad y eficiencia en el manejo de grandes volúmenes de información.

In [2]:
import numpy as np

# Creación de un arreglo simple (matriz)
arreglo = np.array([[1, 2, 3], [4, 5, 6]])

print("Arreglo NumPy:")
print(arreglo)

# Mostrar la forma del arreglo (filas, columnas)
print(f"\nForma (shape): {arreglo.shape}")

Arreglo NumPy:
[[1 2 3]
 [4 5 6]]

Forma (shape): (2, 3)

---

<a id='-pandas'></a>
## 🔹 2: PANDAS: CARGA Y MANIPULACIÓN DE DATOS

Pandas es la herramienta principal para trabajar con datos tabulares. Utilizaremos el archivo `hrdata.csv` como nuestra fuente principal.

### 📝 2.1 Carga de datos y transformación

Importamos la librería y cargamos el archivo CSV estableciendo la columna `Name` como el identificador principal (índice). Además, convertiremos las fechas a un formato que Python pueda manipular.

In [3]:
import pandas as pd

# Lectura del archivo estableciendo el índice
df = pd.read_csv("hrdata.csv", index_col="Name")

# Conversión de la columna 'Hire Date' a tipo datetime
df["Hire Date"] = pd.to_datetime(df["Hire Date"], format="%m/%d/%y")

print("Datos cargados y transformados:")
df.head()

Datos cargados y transformados:

                Hire Date   Salary  Sick Days remaining
Name
Graham Chapman 2014-03-15  50000.0                   10
John Cleese    2015-06-01  65000.0                    8
Eric Idle      2014-05-12  45000.0                   10
Terry Jones    2013-11-01  70000.0                    3
Terry Gilliam  2014-08-12  48000.0                    7

### 📝 2.2 Extracción de Componentes de Fecha

Utilizando el accesorio `.dt`, podemos descomponer la fecha en sus partes elementales para enriquecer nuestro DataFrame.

In [4]:
# Creación de nuevas columnas a partir de la fecha de contratación
df["Year"] = df["Hire Date"].dt.year
df["Month"] = df["Hire Date"].dt.month
df["Day"] = df["Hire Date"].dt.day
df["DayName"] = df["Hire Date"].dt.day_name()

print("DataFrame actualizado con columnas de fecha:")
df.head()

DataFrame actualizado con columnas de fecha:

,Hire Date,Salary,Sick Days remaining,Year,Month,Day,DayName
Name,,,,,,,
Graham Chapman,2014-03-15,50000.0,10,2014,3,15,Saturday
John Cleese,2015-06-01,65000.0,8,2015,6,1,Monday
Eric Idle,2014-05-12,45000.0,10,2014,5,12,Monday
Terry Jones,2013-11-01,70000.0,3,2013,11,1,Friday
Terry Gilliam,2014-08-12,48000.0,7,2014,8,12,Tuesday

### 📝 2.3 Inspección Básica del DataFrame

Es esencial inspeccionar los datos para entender su estructura y contenido.

In [5]:
# 1. Dimensiones (Filas, Columnas)
print(f"Forma: {df.shape}")

# 2. Resumen técnico (tipos de datos, nulos)
print("\nInformación detallada:")
df.info()

# 3. Primeras 5 filas por defecto
print("\nPrimeras filas:")
print(df.head())

# 4. Muestra aleatoria de 2 registros
print("\nMuestra aleatoria:")
print(df.sample(2))

# 5. Estadísticas descriptivas básicas
print("\nResumen estadístico:")
print(df.describe())

Forma: (6, 7)

Información detallada:
<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Graham Chapman to Michael Palin
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Hire Date            6 non-null      datetime64[ns]
 1   Salary               6 non-null      float64
 2   Sick Days remaining  6 non-null      int64
 3   Year                 6 non-null      int32
 4   Month                6 non-null      int32
 5   Day                  6 non-null      int32
 6   DayName              6 non-null      object
dtypes: datetime64[ns](1), float64(1), int32(3), int64(1), object(1)
memory usage: 312.0+ bytes

Primeras filas:
                Hire Date   Salary  Sick Days remaining  Year  Month  Day  \
Name
Graham Chapman 2014-03-15  50000.0                   10  2014      3   15
John Cleese    2015-06-01  65000.0                    8  2015      6    1
Eric Idle      2014-05-12  45000.0                   10  2014      5   12
Terry Jones    2013-11-01  70000.0                    3  2013     11    1
Terry Gilliam  2014-08-12  48000.0                    7  2014      8   12

                 DayName
Name
Graham Chapman  Saturday
John Cleese       Monday
Eric Idle         Monday
Terry Jones       Friday
Terry Gilliam    Tuesday

Muestra aleatoria:
             Hire Date   Salary  Sick Days remaining  Year  Month  Day DayName
Name
Terry Jones 2013-11-01  70000.0                    3  2013     11    1  Friday
Eric Idle   2014-05-12  45000.0                   10  2014      5   12  Monday

Resumen estadístico:
                 Hire Date        Salary  Sick Days remaining         Year  \
count                    6      6.000000             6.000000     6.000000
mean   2014-04-20 20:00:00  57333.333333             7.666667  2013.833333
min    2013-05-23 00:00:00  45000.000000             3.000000  2013.000000
25%    2013-12-04 12:00:00  48500.000000             7.250000  2013.250000
50%    2014-04-13 00:00:00  57500.000000             8.000000  2014.000000
75%    2014-07-20 00:00:00  65750.000000             9.500000  2014.000000
max    2015-06-01 00:00:00  70000.000000            10.000000  2015.000000
std                    NaN  10838.204033             2.581989     0.752773

           Month        Day
count   6.000000   6.000000
mean    6.333333  10.666667
min     3.000000   1.000000
25%     5.000000   3.750000
50%     5.500000  12.000000
75%     7.500000  14.250000
max    11.000000  23.000000
std     2.804758   8.500980

---

<a id='-series'></a>
## 🔹 3: MANEJO DE SERIES

Una **Series** es un arreglo unidimensional capaz de contener cualquier tipo de datos. Esencialmente, es una columna individual.

In [6]:
# Creación de una Series con índices personalizados
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

print("Series obj2:")
print(obj2)

# Acceso a elementos por etiqueta
print(f"\nValor en el índice 'd': {obj2['d']}")

# Aplicación de máscaras booleanas y comparaciones
print("\nValores en obj2 que son mayores a 0:")
print(obj2[obj2 > 0])

Series obj2:
d    4
b    7
a   -5
c    3
dtype: int64

Valor en el índice 'd': 4

Valores en obj2 que son mayores a 0:
d    4
b    7
c    3
dtype: int64

---

<a id='-dataframes'></a>
## 🔹 4: DATAFRAMES: CREACIÓN Y OPERACIONES

El **DataFrame** representa una estructura de datos bidimensional (tablas) con colecciones de columnas ordenadas.

### 📝 4.1 Creación del DataFrame

Podemos construir un DataFrame desde un diccionario de Python.

In [7]:
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}
df_states = pd.DataFrame(data)

print("DataFrame creado:")
print(df_states)

DataFrame creado:
    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

### 📝 4.2 Reordenamiento de Columnas

Podemos reorganizar las columnas pasando una lista con el orden deseado.

In [8]:
# Definir el nuevo orden de columnas
cols = ["year", "state", "pop"]
print("DataFrame reordenado:")
print(df_states[cols])

DataFrame reordenado:
   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

### 📝 4.3 Acceso a Columnas

Existen dos formas principales de acceder a los datos de una columna específica.

In [9]:
# Acceso con corchetes (clave de diccionario)
print("Columna 'state' (Forma corchetes):")
print(df_states["state"])

# Acceso con punto (atributo)
print("\nColumna 'state' (Forma punto):")
print(df_states.state)

Columna 'state' (Forma corchetes):
0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

Columna 'state' (Forma punto):
0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

### 📝 4.4 Agregar una Columna

Es posible insertar nuevas columnas con valores constantes o secuencias.

In [10]:
# Agregar columna 'dept' con valores incrementales
df_states["dept"] = np.arange(6.)

print("DataFrame con nueva columna:")
print(df_states)

DataFrame con nueva columna:
    state  year  pop  dept
0    Ohio  2000  1.5   0.0
1    Ohio  2001  1.7   1.0
2    Ohio  2002  3.6   2.0
3  Nevada  2001  2.4   3.0
4  Nevada  2002  2.9   4.0
5  Nevada  2003  3.2   5.0

### 📝 4.5 Eliminar Filas o Columnas

El método `.drop()` se utiliza para remover elementos. Por defecto devuelve una **copia** del DataFrame; si queremos modificar el original debemos usar `inplace=True`.

*   `axis=0`: Indica que se eliminarán filas.
*   `axis=1`: Indica que se eliminarán columnas.

In [11]:
# DataFrame de prueba para eliminación
demo_df = pd.DataFrame(np.arange(16).reshape((4, 4)),
                      index=["Ohio", "Colorado", "Utah", "New York"],
                      columns=["one", "two", "three", "four"])

# 1. Eliminar fila 'Colorado' (devuelve una copia)
print("Resultado de eliminar 'Colorado' (copia):")
print(demo_df.drop("Colorado"))

# 2. Eliminar fila 'Ohio' modificando el original (inplace)
demo_df.drop("Ohio", inplace=True)

# 3. Eliminar columnas usando axis=1
limpio_df = demo_df.drop(["two", "four"], axis=1)

print("\nDataFrame final después de las eliminaciones:")
print(limpio_df)

Resultado de eliminar 'Colorado' (copia):
          one  two  three  four
Ohio        0    1      2     3
Utah        8    9     10    11
New York   12   13     14    15

DataFrame final después de las eliminaciones:
          one  three
Colorado    4      6
Utah        8     10
New York   12     14

### 📝 4.6 Selección con loc e iloc

`.loc` realiza selecciones basadas en **etiquetas**, mientras que `.iloc` se basa en **posiciones enteras**.

In [12]:
# Selección por etiqueta con .loc
print("Selección de la fila 'Utah' con .loc:")
print(limpio_df.loc["Utah"])

# Selección por posición con .iloc
print("\nSelección de la primera fila con .iloc:")
print(limpio_df.iloc[0])

Selección de la fila 'Utah' con .loc:
one       8
three    10
Name: Utah, dtype: int64

Selección de la primera fila con .iloc:
one      4
three    6
Name: Colorado, dtype: int64

---

<a id='-filtros'></a>
## 🔹 5: MÁSCARAS Y FILTROS

Los filtros nos permiten extraer subconjuntos de datos que cumplen con criterios lógicos específicos.

In [13]:
# 1. Máscara booleana simple
print("Máscara (Salario > 60k):")
mask = df["Salary"] > 60000
print(df[mask])

# 2. Filtros con condiciones compuestas (& = y)
filtro_comp = df[(df["Salary"] > 50000) & (df["Sick Days remaining"] > 5)]
print("\nResultado de filtro compuesto:")
print(filtro_comp)

# 3. Selección específica con .loc y máscara
print("\nSueldos de empleados contratados después del 2013:")
print(df.loc[df["Year"] > 2013, ["Salary"]])

# 4. Uso pequeño de lambda para filtrar
print("\nFiltro rápido con lambda (Sueldo > 65k):")
print(df[lambda x: x["Salary"] > 65000])

Máscara (Salario > 60k):
               Hire Date   Salary  Sick Days remaining  Year  Month  Day  \
Name
John Cleese   2015-06-01  65000.0                    8  2015      6    1
Terry Jones   2013-11-01  70000.0                    3  2013     11    1
Michael Palin 2013-05-23  66000.0                    8  2013      5   23

                DayName
Name
John Cleese      Monday
Terry Jones      Friday
Michael Palin  Thursday

Resultado de filtro compuesto:
               Hire Date   Salary  Sick Days remaining  Year  Month  Day  \
Name
John Cleese   2015-06-01  65000.0                    8  2015      6    1
Michael Palin 2013-05-23  66000.0                    8  2013      5   23

                DayName
Name
John Cleese      Monday
Michael Palin  Thursday

Sueldos de empleados contratados después del 2013:
                 Salary
Name
Graham Chapman  50000.0
John Cleese     65000.0
Eric Idle       45000.0
Terry Gilliam   48000.0

Filtro rápido con lambda (Sueldo > 65k):
               Hire Date   Salary  Sick Days remaining  Year  Month  Day  \
Name
Terry Jones   2013-11-01  70000.0                    3  2013     11    1
Michael Palin 2013-05-23  66000.0                    8  2013      5   23

                DayName
Name
Terry Jones      Friday
Michael Palin  Thursday

---

<a id='-sort'></a>
## 🔹 6: ORDENAMIENTO (SORT)

Podemos organizar las filas de una tabla basándonos en sus valores o en sus índices.

In [14]:
# Ordenar por valores de una columna (ej. Salario descendente)
print("Ordenado por Salario (Descendente):")
print(df.sort_values(by="Salary", ascending=False))

# Ordenar por el índice (Alfabético por nombre)
print("\nOrdenado por Índice:")
print(df.sort_index())

Ordenado por Salario (Descendente):
                Hire Date   Salary  Sick Days remaining  Year  Month  Day  \
Name
Terry Jones    2013-11-01  70000.0                    3  2013     11    1
Michael Palin  2013-05-23  66000.0                    8  2013      5   23
John Cleese    2015-06-01  65000.0                    8  2015      6    1
Graham Chapman 2014-03-15  50000.0                   10  2014      3   15
Terry Gilliam  2014-08-12  48000.0                    7  2014      8   12
Eric Idle      2014-05-12  45000.0                   10  2014      5   12

                 DayName
Name
Terry Jones       Friday
Michael Palin   Thursday
John Cleese       Monday
Graham Chapman  Saturday
Terry Gilliam    Tuesday
Eric Idle         Monday

Ordenado por Índice:
                Hire Date   Salary  Sick Days remaining  Year  Month  Day  \
Name
Eric Idle      2014-05-12  45000.0                   10  2014      5   12
Graham Chapman 2014-03-15  50000.0                   10  2014      3   15
John Cleese    2015-06-01  65000.0                    8  2015      6    1
Michael Palin  2013-05-23  66000.0                    8  2013      5   23
Terry Gilliam  2014-08-12  48000.0                    7  2014      8   12
Terry Jones    2013-11-01  70000.0                    3  2013     11    1

                 DayName
Name
Eric Idle         Monday
Graham Chapman  Saturday
John Cleese       Monday
Michael Palin   Thursday
Terry Gilliam    Tuesday
Terry Jones       Friday